org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod Properties
maven_group = com.erfanmirdehghan
archives_base_name = sonar-bypass

# Proxy (در صورت نیاز از پروکسی خودت استفاده کن)
# systemProp.http.proxyHost=192.168.1.2
# systemProp.http.proxyPort=8090
# systemProp.https.proxyHost=192.168.1.2
# systemProp.https.proxyPort=8090